# Generated by Django 4.1.7 on 2023-02-16 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trip.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('nid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.IntegerField(choices=[(1, 'Long'), (2, 'Short')], default=1)),
                ('max_trip', models.IntegerField(default=1)),
                ('route_order', models.IntegerField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=127)),
                ('model', models.CharField(blank=True, max_length=127, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Heavy'), (2, 'Light')], default=1)),
                ('using_date', models.DateField(default=django.utils.timezone.now)),
                ('cycle', models.IntegerField(default=1)),
                ('condition', models.IntegerField(choices=[(0, 'Not OK'), (1, 'OK'), (2, 'Not Assigned')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=models.SET(trip.models.Vehicle.pick_a_difault_driver), to='trip.driver')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='trip.vehicle')),
            ],
            options={
                'db_table': 'vehicle_conditions',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('vehicle_cycle', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Trip Assigned'), (2, 'Left From Dhaka'), (3, 'Arrived To Destination'), (4, 'Left From Destination'), (5, 'Completed')], default=1)),
                ('leaving_time_from_dhaka', models.DateTimeField(default=django.utils.timezone.now)),
                ('arriving_time_to_destination', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaving_time_from_destination', models.DateTimeField(default=django.utils.timezone.now)),
                ('arriving_time_to_dhaka', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrived_to_destination_updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_updated_to_destination', to=settings.AUTH_USER_MODEL)),
                ('arrived_to_dhaka_updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_updated_to_dhaka', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.route')),
                ('left_from_destination_updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_updated_from_destination', to=settings.AUTH_USER_MODEL)),
                ('left_from_dhaka_updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_updated_from_dhaka', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-id', '-date', 'status'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='reserved_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle'),
        ),
    ]
